-- MySQL Script generated by MySQL Workbench
-- Fri Jun 12 10:25:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TrafficoAereoInternazionale
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrafficoAereoInternazionale
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrafficoAereoInternazionale` DEFAULT CHARACTER SET utf8 ;
USE `TrafficoAereoInternazionale` ;

-- -----------------------------------------------------
-- Table `TrafficoAereoInternazionale`.`aeroporto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficoAereoInternazionale`.`aeroporto` (
  `codice` CHAR(3) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `citta` VARCHAR(45) NOT NULL,
  `nazione` VARCHAR(45) NOT NULL,
  `lunghezza_pista` FLOAT NOT NULL,
  PRIMARY KEY (`codice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrafficoAereoInternazionale`.`tipo_aeromobile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficoAereoInternazionale`.`tipo_aeromobile` (
  `costruttore` VARCHAR(45) NOT NULL,
  `modello` VARCHAR(45) NOT NULL,
  `spazio_atterraggio` FLOAT NOT NULL,
  `numero_passeggeri` INT NOT NULL,
  `numero_motori` TINYINT(4) NOT NULL,
  `lunghezza` FLOAT NOT NULL,
  PRIMARY KEY (`costruttore`, `modello`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrafficoAereoInternazionale`.`compatibilita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficoAereoInternazionale`.`compatibilita` (
  `aeroporto` CHAR(3) NOT NULL,
  `costruttore` VARCHAR(45) NOT NULL,
  `modello` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aeroporto`, `costruttore`, `modello`),
  INDEX `aeromobile_idx` (`costruttore` ASC, `modello` ASC) VISIBLE,
  CONSTRAINT `aeroporto`
    FOREIGN KEY (`aeroporto`)
    REFERENCES `TrafficoAereoInternazionale`.`aeroporto` (`codice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `aeromobile`
    FOREIGN KEY (`costruttore` , `modello`)
    REFERENCES `TrafficoAereoInternazionale`.`tipo_aeromobile` (`costruttore` , `modello`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrafficoAereoInternazionale`.`alleanza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficoAereoInternazionale`.`alleanza` (
  `codice` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `anno_fondazione` VARCHAR(45) NOT NULL,
  `Frequent_flyer` VARCHAR(45) NOT NULL,
  `sede` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrafficoAereoInternazionale`.`compagnia_aerea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficoAereoInternazionale`.`compagnia_aerea` (
  `codice` CHAR(2) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sede` VARCHAR(45) NOT NULL,
  `anno_fondazione` VARCHAR(45) NOT NULL,
  `alleanza` INT NULL,
  PRIMARY KEY (`codice`),
  INDEX `alleanza_idx` (`alleanza` ASC) VISIBLE,
  CONSTRAINT `alleanza`
    FOREIGN KEY (`alleanza`)
    REFERENCES `TrafficoAereoInternazionale`.`alleanza` (`codice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrafficoAereoInternazionale`.`aeromobile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficoAereoInternazionale`.`aeromobile` (
  `codice` VARCHAR(45) NOT NULL,
  `anno_immatricolazione` DATE NOT NULL,
  `miglia_percorse` FLOAT NOT NULL,
  `costruttore` VARCHAR(45) NOT NULL,
  `modello` VARCHAR(45) NOT NULL,
  `compagnia_aerea` CHAR(2) NOT NULL,
  PRIMARY KEY (`codice`),
  INDEX `costruttore_idx` (`costruttore` ASC) VISIBLE,
  INDEX `modello_idx` (`modello` ASC) VISIBLE,
  INDEX `compagnia_idx` (`compagnia_aerea` ASC) VISIBLE,
  CONSTRAINT `costruttore`
    FOREIGN KEY (`costruttore`)
    REFERENCES `TrafficoAereoInternazionale`.`tipo_aeromobile` (`costruttore`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `modello`
    FOREIGN KEY (`modello`)
    REFERENCES `TrafficoAereoInternazionale`.`tipo_aeromobile` (`modello`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `compagnia`
    FOREIGN KEY (`compagnia_aerea`)
    REFERENCES `TrafficoAereoInternazionale`.`compagnia_aerea` (`codice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrafficoAereoInternazionale`.`volo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficoAereoInternazionale`.`volo` (
  `codice` INT NOT NULL,
  `data` DATE NOT NULL,
  `orario_partenza` DATETIME NOT NULL,
  `orario_arrivo` DATETIME NOT NULL,
  `stato` ENUM('schedulato', 'in volo', 'atterrato', 'ritardato', 'cancellato') NOT NULL,
  `aeroporto_partenza` CHAR(3) NOT NULL,
  `aeroporto_arrivo` CHAR(3) NOT NULL,
  `aeromobile` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codice`, `data`),
  INDEX `partenza_idx` (`aeroporto_partenza` ASC) VISIBLE,
  INDEX `arrivo_idx` (`aeroporto_arrivo` ASC) VISIBLE,
  INDEX `aeromobile_idx` (`aeromobile` ASC) VISIBLE,
  CONSTRAINT `partenza`
    FOREIGN KEY (`aeroporto_partenza`)
    REFERENCES `TrafficoAereoInternazionale`.`aeroporto` (`codice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `arrivo`
    FOREIGN KEY (`aeroporto_arrivo`)
    REFERENCES `TrafficoAereoInternazionale`.`aeroporto` (`codice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `aeromobile`
    FOREIGN KEY (`aeromobile`)
    REFERENCES `TrafficoAereoInternazionale`.`aeromobile` (`codice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrafficoAereoInternazionale`.`hub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficoAereoInternazionale`.`hub` (
  `aeroporto` CHAR(3) NOT NULL,
  `alleanza` INT NOT NULL,
  `numero_hangar` INT NOT NULL,
  PRIMARY KEY (`aeroporto`, `alleanza`),
  INDEX `alleanza_idx` (`alleanza` ASC) VISIBLE,
  CONSTRAINT `aeroporto`
    FOREIGN KEY (`aeroporto`)
    REFERENCES `TrafficoAereoInternazionale`.`aeroporto` (`codice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `alleanza`
    FOREIGN KEY (`alleanza`)
    REFERENCES `TrafficoAereoInternazionale`.`alleanza` (`codice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
